# Docker compose file format version
version: "3.9"

services:

  payment-service:
    build: ./app-services/payment-service
    image: app-services/payment-service
    container_name: payment-service

    ports:
      - "8082:8082"

  inventory-service:
    build: ./app-services/inventory-service
    image: app-services/inventory-service
    container_name: inventory-service

    ports:
      - "8083:8083"

  order-service:
    # build it first
    build: ./app-services/order-service
    # service name used by docker compose
    image: app-services/order-service

    container_name: order-service
    ports:
      - "8081:8081"

    environment:
      - SPRING_PROFILES_ACTIVE=docker

    # ensures dependant services are started first, doesn't have to in healthy state
    depends_on:
      - payment-service
      - inventory-service